name: C/C++ CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  x86_64-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install packages
        run: sudo apt update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev nasm qemu-system xorriso mtools grub-pc-bin grub-common
      - name: fetch submodule
        run: git submodule update --init
      - name: Restore toolchain cache
        id: cache-toolchain
        uses: actions/cache@v3
        with:
          path: toolchain/
          key: toolchain-x86_64-${{ hashFiles('**/Makefile', '**/toolchain/**', '**/build-scripts/**') }}
          restore-keys: |
            toolchain-x86_64-
            toolchain-
      - name: build an x86_64 ISO
        run: make
      - name: Set date output
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Rename ISO file
        run: cp build/myos.iso monolith-${{ steps.date.outputs.date }}-x86_64.iso
      - name: Upload x86_64 ISO
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-iso
          path: monolith-${{ steps.date.outputs.date }}-x86_64.iso

  i386-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install packages
        run: sudo apt update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev nasm qemu-system xorriso mtools grub-pc-bin grub-common
      - name: fetch submodule
        run: git submodule update --init
      - name: Restore toolchain cache
        id: cache-toolchain
        uses: actions/cache@v3
        with:
          path: toolchain/
          key: toolchain-i386-${{ hashFiles('**/Makefile', '**/toolchain/**', '**/build-scripts/**') }}
          restore-keys: |
            toolchain-i386-
            toolchain-
      - name: build an i386 ISO
        run: ARCH="pc/i386" make
      - name: Set date output
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Rename ISO file
        run: cp build/myos.iso monolith-${{ steps.date.outputs.date }}-i386.iso
      - name: Upload i386 ISO
        uses: actions/upload-artifact@v4
        with:
          name: i386-iso
          path: monolith-${{ steps.date.outputs.date }}-i386.iso

  create-release:
    needs: [x86_64-build, i386-build]
    runs-on: ubuntu-latest
    steps:
      - name: Set date output
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Download x86_64 ISO
        uses: actions/download-artifact@v4
        with:
          name: x86_64-iso
      - name: Download i386 ISO
        uses: actions/download-artifact@v4
        with:
          name: i386-iso
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            monolith-${{ steps.date.outputs.date }}-x86_64.iso
            monolith-${{ steps.date.outputs.date }}-i386.iso
          name: Release ${{ steps.date.outputs.date }}
          tag_name: v${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
